### ISSUE TITLE
[FE] 상황별 페이지 적용

### ISSUE THREAD

**Issue by chaelotus** [codestates-seb/seb44_main_028#108]
### ISSUE
* Group: client
* Type: feature
* Detail: 상황별로 404, Loading, 검색 결과 없는 컴포넌트 보여주기

### TODO
- [x] 로딩 중 페이지 적용
- [x] 404 에러 페이지 적용
- [x] 검색 결과 없을 때 페이지 적용

### Estimated time
```2h```
