### ISSUE TITLE
[FE] 카테고리별 페이지

### ISSUE THREAD

**Issue by chaelotus** [codestates-seb/seb44_main_028#109]
### ISSUE
* Group: client, server, sr
* Type: bug, feature, delete
* Detail: fix actions from client redux

### TODO
- [x] 카테고리 페이지 옵션 드롭다운 구현
- [x] 로그인 하지 않은 유저가 거리 위치 필터 선택하면 로그인 페이지로 리다이렉션
- [ ] 필터한 선택한 상품리스트들을 화면에 띄운다.
- [x] 상품 무한 스크롤로 구현한다.
- [ ] 할 수 있다면 스켈레톤까지

### Estimated time
```1day```
