### ISSUE TITLE
[BE]회원 정보 조회, 수정, 삭제 기능 구현

### ISSUE THREAD

**Issue by ahyoung227** [codestates-seb/seb44_main_028#12]
### ISSUE
* Group: server
* Type: feature
* Detail: 회원정보 CRUD 기능구현

### TODO
- [x] 회원 정보 조회
- [x] 회원 정보 수정
- [x] 회원 정보 삭제
- [x] 테스트

### Estimated time
```10h```
