### ISSUE TITLE
[FE] 마이페이지

### ISSUE THREAD

**Issue by chaelotus** [codestates-seb/seb44_main_028#252]
### ISSUE
마이페이지에서 유저가 빌려준 내역, 빌린 내역, 관심 목록을 확인할 수 있다.
유저의 위치, 닉네임, 사진 수정을 할 수 있다.

### TODO
- 빌린내역 
  - [x] 취소버튼 누르면 사라지게 구현
  - [x]  취소 된 내역에 있는 상품의 취소시간이 예약시작 날짜로 되어있는 점 수정

빌려준내역 
  - [ ] 예약 시작 -  종료 날짜 화면에 띄우기
  - [ ] 상품을 누르면 버튼 나오도록 구현
  - [ ] 각각의 버튼 예약 요청, 예약확정, 예약취소 , 지난예약 을 누르면 빌린 사람 카드가 나와야한다

회원정보수정
  - [ ] 이미지, 닉네임 수정

### Estimated time
1 day
