### ISSUE TITLE
[FE] 공통 컴포넌트 구현 1

### ISSUE THREAD

**Issue by chaelotus** [codestates-seb/seb44_main_028#26]
### ISSUE
* Group: client
* Type: feature
* Detail: 공통 컴포넌트 구현

### TODO
- [x] 상품카드 컴포넌트 구현
- [x] 태그 컴포넌트 구현
- [x] 모달창 컴포넌트 구현
  - [x] 외부 영역 누르면 모달창 닫히게 구현
- [ ] 알림 toast 구현
- [x] 카테고리 버튼 구현
- [x] 드롭다운 구현

### Estimated time
Pick one
```8h```
