### ISSUE TITLE
[FE] 헤더 구현

### ISSUE THREAD

**Issue by chaelotus** [codestates-seb/seb44_main_028#27]
### ISSUE
* Group: client
* Type: feature
* Detail: 헤더 구현

### TODO
- [ ]  헤더
    - [x]  로고 클릭 시 메인페이지로 이동
    - [x]  마이페이지 클릭 시 마이페이지로 이동
    - [x]  글 작성하기 클릭 시 글 작성 페이지로 이동
    - [x]  검색 아이콘 누르면 검색 창 생기도록 애니메이션
    - [x]  채팅 아이콘 누르면 채팅 페이지로 이동
    - [x]  로그인 아이콘 `hover`시 말풍선으로 로그인 글 보이게 구현
    - [x]  로그인 아이콘 클릭 시 로그인 페이지로 이동
    - [ ]  로그인 된 상황이면 logout으로 보이게 구현

### Estimated time
Pick one
```5h```
