### ISSUE TITLE
[FE] 카테고리 버튼 구현

### ISSUE THREAD

**Issue by chaelotus** [codestates-seb/seb44_main_028#35]
### ISSUE
* Group: client
* Type: feature
* Detail: 카테고리 버튼 구현

### TODO
- [x] 메인페이지에서 10개의 카테고리 버튼 구현
- [x] 각각의 카테고리별 상세페이지에 GET 요청을 받아 해당되는 데이터들을 받아온다.
- [x] 정해진 위치에 배치한다.
- [x] 카테고리 클릭하면 해당 페이지로 이동할 수 있다.

### Estimated time
Pick one
```1h```
