### ISSUE TITLE
[FE] 배너 스와이퍼 구현

### ISSUE THREAD

**Issue by chaelotus** [codestates-seb/seb44_main_028#39]
### ISSUE
* Group: client
* Type: feature
* Detail: 배너 스와이퍼 구현

### TODO
- [x] 4개의 사진을 오른쪽 화살표 버튼을 누르면 움직일 수 있게 한다.
- [x] 5초마다 사진들이 넘어갈 수 있도록 한다.
- [ ] 사진이 넘어가 듯 보이게 애니메이션

### Estimated time
Pick one
```3h```
